// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

interface TestTypeDocumentData {}

/**
 * Test type document from Prismic
 *
 * - **API ID**: `test_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestTypeDocumentData>,
    "test_type",
    Lang
  >;

export type AllDocumentTypes = TestTypeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type { TestTypeDocument, TestTypeDocumentData, AllDocumentTypes };
  }
}
