// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_banner: dynamic(() => import("./HeroBanner")),
  navigation_menu_item: dynamic(() => import("./NavigationMenuItem")),
  newsletter: dynamic(() => import("./NewsletterBanner")),
  whats_on: dynamic(() => import("./WhatsOn")),
};
