// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_whats_on: dynamic(() => import("./FeaturedWhatsOn")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  navigation_menu_item: dynamic(() => import("./NavigationMenuItem")),
  newsletter: dynamic(() => import("./NewsletterBanner")),
};
