import type { Metadata } from "next";
import "./globals.css";
import { headingFont, bodyFont } from './fonts';

import Navbar from "./components/Navbar";
import { getNavigation } from "@/prismicio"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const navSlices = await getNavigation()
  return (
    <html lang="en" className={`${headingFont.variable} ${bodyFont.variable} antialiased`}>
      <body>
        <Navbar slices={navSlices} />
        <main>{children}</main>
      </body>
    </html>
  );
}